### ISSUE TITLE
reopen: "Duplicate rows added on window resize"

### ISSUE THREAD

**Issue by yarf** [NeXTs/Clusterize.js#100]
(reopening, since it's not clear whether you noticed additional commentary on #98 after it was closed)

I'm afraid the commit doesn't quite address the issue effectively -- the very next call to update(), either before or after switching back from another tab, causes the same issue to occur.

http://codepen.io/anon/pen/PpwBGV

... added an update() timer at the bottom to emulate the behavior

**Comment by NeXTs** [comment]
@yarf Hi, did you have a chance to test this? Does it works as expected?

**Comment by yarf** [comment]
yup, that did it!

Do we now get a free commercial-license for being part of your QA team? ;-)

*cough*

**Comment by NeXTs** [comment]
I'm glad it helped!

Uplabs is responsible for licenses, not me :P
