### ISSUE TITLE
Bootstrap table example?

### ISSUE THREAD

**Issue by krosoftware** [NeXTs/Clusterize.js#102]
Hello
is there any demo of how to "clusterize" Bootstrap table, please?
Thank you.

**Comment by NeXTs** [comment]
How bootstrap's table differs from common table?

..correct, it has additional classes. So that just add bootstrap's classes to table's layout that provided in Clusterize' docs.
JS will be same as at example in docs

**Comment by krosoftware** [comment]
Thank you but if I know how to do that then I will not ask.
If you can provide some example, I will be grateful.
