### ISSUE TITLE
Basic usage issue

### ISSUE THREAD

**Issue by dinkom** [NeXTs/Clusterize.js#104]
Hi,

I'm attempting to render a large table (such as the one in your 500k example), but I'm obviously doing something wrong.

I have an array like this:
`
var data = ["<tr><td>fizz</td><td>buzz</td><td>bar</td></tr>", ...]
`

My JS is:
`
var clusterize = new Clusterize({
    rows: data,
    scrollId: 'scrollArea',
    contentId: 'contentArea'
});
`

The HTML is also copy-pasted from your website (without the 'Loading data...' part).

I included the library like this:
```
<link href="https://cdnjs.cloudflare.com/ajax/libs/clusterize.js/0.17.6/clusterize.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/clusterize.js/0.17.6/clusterize.min.js"></script>
```

I do get some data rendered, but it ends with:
```
<tr class="clusterize-extra-row clusterize-bottom-space" style="height: 2.19956e+07px;"></tr>
```

and if I continue scrolling, it's just a blank screen, although I am still inside the `#contentArea`.

Can you tell me what am I doing wrong? 
Thanks!

**Comment by NeXTs** [comment]
Hi
Everything seems to be fine in your settings.
It hugely depends on content in your `data` array. Please provide reproducible example at codepen

**Comment by dinkom** [comment]
Ok, here's the link: https://codepen.io/dinkom/pen/xqLGNb
It's the same even if I drastically reduce the size of data (from 1 million to 10k, for instance). Also, codepen thinks I have an infinite loop when I create a million entries, but I'm guessing it's just because it takes some time to run. If you try with 10k cap, the warning disappears, but it still doesn't work as expected.

**Comment by NeXTs** [comment]
You missed Clusterize's styles. That's it

**Comment by dinkom** [comment]
Locally, I had styles included... but you still solved the problem for me because now I know that styles were the issue... so I took one more look at them - and I saw I didn't write `rel="stylesheet"` in the link... so I basically didn't include them 😭 

Thanks man, I owe you a beer 🍺

**Comment by NeXTs** [comment]
you are welcome :)
\
