### ISSUE TITLE
The demo is smoother without Clusterize.js

### ISSUE THREAD

**Issue by nudefireninja** [NeXTs/Clusterize.js#108]
Scrolling is smoother without Clusterize.js:

https://gfycat.com/AltruisticWeakBronco

System:
Mac OS X 10.9.5
MacBook Pro 2011 17"
2.4GHz i7
AMD Radeon 6770M

Browser:
Firefox 53.0.2 (no addons)

**Comment by NeXTs** [comment]
Hey, yeah FF support this feature natively

take a look at https://github.com/NeXTs/Clusterize.js/issues/93
