### ISSUE TITLE
Fixed Columns 

### ISSUE THREAD

**Issue by HarshadBatale** [NeXTs/Clusterize.js#109]
Dear Sir,

Does any way clusterize framework support for fixed columns and rest of the columns are part of horizontal scrolling  ?

**Comment by NeXTs** [comment]
Hello

I didn't get it, could you please describe it in details

**Comment by Thrilleratplay** [comment]
I believe @HarshadBatale is asking about a feature like [Handsontable's frozen columns feature](https://docs.handsontable.com/0.15.1/demo-freezing.html).

**Comment by HarshadBatale** [comment]
Dear Sir,
Yes I want to ask what  Thrilleratplay has said.
I mean  frozen columns feature along with header row fix.
Regards
Harshad Batale

**Comment by NeXTs** [comment]
Nope, I don't see an easy way to implement that using clusterize
