### ISSUE TITLE
Using page-down causes strange behavior

### ISSUE THREAD

**Issue by as-com** [NeXTs/Clusterize.js#11]
1. Click into one of the clusterized things on the demo page.
2. Press page down repeatedly
3. The list will become unfocused at the end of each cluster and page down will scroll the page.

**Comment by dfsq** [comment]
This is default browser behavior, it's not anything Clusterize.js specific, there is nothing wrong with it. Check this simple demo http://jsfiddle.net/6eg30sko/

**Comment by cead22** [comment]
Same happens when you scroll down normally on the container in the demo page, the whole page will scroll down
