### ISSUE TITLE
Plugin shows only first cluster, others are blank.

### ISSUE THREAD

**Issue by PrzemekP1980** [NeXTs/Clusterize.js#111]
I've started testing Clusterize plugin to check if it'll work with my new project.
It handles data quite when it gets to speed, unfortunately it shows only first cluster of data (default 200 rows - unless I change **rows_in_block** or **blocks_in_cluster** options.
It seems that table is long enough but everything beside first cluster is blank.
All I've got from console is:
`<tr class="clusterize-extra-row clusterize-bottom-space" style="height: 1.11497e+07px;"></tr>`
Any thoughts ?

I've manged to replicate this problem on codepen.io
[https://codepen.io/anon/pen/RVXayy](https://codepen.io/anon/pen/RVXayy)

**Comment by Thrilleratplay** [comment]
In the pen you provided, I have no problem seeing all of the rows in `data` in Chrome, but I am scrolling the entire page.  I forked your pen, added the clusterize.css styling and basic table styles to visually clarify where the cells and table are.  https://codepen.io/anon/pen/yXBaGq.

Does the problem you are seeing still exists in the forked pen?

**Comment by NeXTs** [comment]
Hey @PrzemekP1980 
You've added Clusterize styles but forgot to add necessary classes.
That "clusterize-scroll" class is important :)

**Comment by PrzemekP1980** [comment]
@Thrilleratplay - thanks for your answer. In your pen all is working fine.
@NeXTs - I've forgot to add this class in the pen, but on my project this class isn't missing. 
As you can see in the image: [http://pietruszka.eu/zrzut.png](http://pietruszka.eu/zrzut.png) - "clusterize-scroll" class is there, but there is still a lot of white space in the table.

**Comment by allanlaal** [comment]
I'm having the same exact issue with ul's - I've doublechecked everything and still it only displays 200 (rows_in_block * blocks_in_cluster) rows and nothing more. although getRowsAmount() has the correct number of rows (~6700)


		<div id="dashboard_list_container" class="clusterize-scroll">
			<ul 
				id="dashboard_list"
				category="starred" 
				class="category_default todo_item_list clusterize-content"
				newest_id=""
			>
			</ul>
		</div>	

and the js side:

	todo_dashboard_list_clusterize_instance = new Clusterize({
		rows:				[], // filled by load_todo_dashboard_list_get via Clusterize.append()
		scrollId:			'dashboard_list_container',
		contentId:			'dashboard_list',
		tag:				'li',
		rows_in_block:		50, // max amount of Todo rows on a normal screen
		blocks_in_cluster:	4,
		show_no_data_row:	true,
		no_data_text:		dashboard_list_load_pageholder,
		no_data_class:		'dashboard_list_loading_indicator',
		keep_parity:		false,
		callbacks: {
			clusterChanged: function() {
				calc_todo_totals();
			}
		}
	});
