### ISSUE TITLE
Can't scroll to a specific element at the end of a big list

### ISSUE THREAD

**Issue by TomCorvus** [NeXTs/Clusterize.js#127]
Hi,

This plugin is really cool. No laggy scroll with 3000 elements. Very interesting!

I have just one problem. When the page is loaded, I try to scroll to a specific element inside a scrollable container but this element doesn't exist in DOM because clusterize.js is already initialized and this element is at the bottom of this container.

Do you have a solution for that?

Thanks

**Comment by TomCorvus** [comment]
Perfect!
Same thing for search. I create an array of the elements of my list, then search in when I type on input.
Just one thing, why is it preferable to render rows by myself with an array of tags in String?
Best performance?

Thanks for your answer

**Comment by NeXTs** [comment]
Instead of handling DOM nodes directly? Yes, that because of memory allocation

**Comment by TomCorvus** [comment]
Great. Thanks for your work!
