### ISSUE TITLE
iOS scrollTo possible bug - inconsistent blank page

### ISSUE THREAD

**Issue by Shaked** [NeXTs/Clusterize.js#130]
Hey, 

Lately I have been playing a lot with Clusterizejs as I am trying to avoid switching my project to React and use Virtual Lists. 

I actually [managed to make it work as expected on mobile/tablet devices](https://pymwymi.io/clusterizejs/) but am experiencing an 1 somewhat critical issue. 

On iPad, when I use the *add to home screen* functionality & open the "web app" from the home screen, I experience an issue where the scrolling is not always working as expected.

As it is quite difficult to explain why and how it works, I have also made a video of ~30 seconds that shows the bug (almost at the end of the video). Generally you will see that after clicking the links on the right side in the example I made, sometimes the view becomes blank and the items are not shown anymore.

The video is available at https://youtu.be/t3OXbd5geKo

*UPDATE #1:*
I think that the bug happens when I click on a link which suppose to scroll to a top value which is already shown in the current cluster, so clicking on the links A & Z seems to always work as expected but clicking on A & B might help you to reproduce the problem. 

I would be happy to provide any information needed.

Thank you
Shaked

**Comment by NeXTs** [comment]
Hey
I can't reproduce this on iphone :(
and I don't have ipad to test this

**Comment by Shaked** [comment]
Can I help somehow? Maybe test things you would have tested?

**Comment by Shaked** [comment]
Seems like this issue is also happening with ReactJS: 
https://www.youtube.com/watch?v=KIDnUovmGVo&feature=youtu.be

https://pymwymi.io/clusterizejs/reactjs/index.html

Maybe it's related to the way iOS is rendering homescreen webapps?

**Comment by Shaked** [comment]
@NeXTs I think that the reply from @clauderic is summarizes this issue quite good.  

> 
> I don't believe this is specifically an issue with react-tiny-virtual-list. It looks like a performance issue, where the device cannot render the requested rows fast enough since your rows are quite heavy to render (multiple images per row).
> 
> The difference in behaviour between when you look at your app in Safari vs an app added to the Home Screen is because the webviews used by both are different. When you look at the app in Safari, it uses WKWebView, which is significantly more performant than UIWebView, which is the webview used for web pages added to the home screen. I don't believe you can specify for a web page added to the home screen to run using WKWebView
> 
> You could look into bundling your app using Cordova instead, which would allow you to specify which webview is used and select WKWebView.

Therefore, I am closing this issue.
Thank you!
