### ISSUE TITLE
creating global variable 'is_mac'

### ISSUE THREAD

**Issue by sgratzl** [NeXTs/Clusterize.js#144]
as far as I can see: 

https://github.com/NeXTs/Clusterize.js/blob/7cd274471e050621a07be3cb40b4fd32e69812a3/clusterize.js#L23

creates a global variable `is_mac` since the `var` keyword is missing

**Comment by NeXTs** [comment]
Hello Samuel

Thanks, but it doesn't create global variable because of `var` declared higher, for `ie` and `,` between them.

**Comment by sgratzl** [comment]
ups I missed that comma
