### ISSUE TITLE
Header inside scrollpane creates spacing when the cluster changes.

### ISSUE THREAD

**Issue by gregorvoinov** [NeXTs/Clusterize.js#149]
HI,

I want to use your clusterize.js, but I have a problem. Above my table there is a bigger header, and that should be scrolled with the table. Therefore, the header and the table are in the same scrollpane. If I scroll now and the first time the table changes the cluster, there is a large spacing to the top of the scrollpane. If I use no header everthing is fine. My question is, is it possible to add multiple elements to the same scrollpane as the table or is that not possible with clusterrize.js?

![image](https://user-images.githubusercontent.com/9499590/40471596-6880706c-5f37-11e8-88ca-a383abaa0663.png)

![image](https://user-images.githubusercontent.com/9499590/40471634-88e32048-5f37-11e8-98dc-25fd99e54303.png)

best regards,
gregor

**Comment by NeXTs** [comment]
Hello

Could you please provide example at codepen?
I'll investigate what can be done

**Comment by gregorvoinov** [comment]
sure thank you very much ;) i will do it tonight, after work.

**Comment by gregorvoinov** [comment]
hi,

a very simplified [codepen](https://codepen.io/destroy90210/pen/XqwxJX)

at line 151, 301, 451.... you can see the effect.

thank you for you effort and support.

**Comment by NeXTs** [comment]
Well, additional element creates additional offset on the top. Unfortunately I don't have easy solution for that, it just wasn't intended to work this way.

**Comment by gregorvoinov** [comment]
That is a pity, then i have to find another solution, but thank you for taking a look.
