### ISSUE TITLE
Data from Markup

### ISSUE THREAD

**Issue by ibnesayeed** [NeXTs/Clusterize.js#15]
It will be nice to allow data to be populated from existing markup. Say, there is a table with a lot of rows in the markup. Grab the data from the markup and remove it from the DOM tree. Clustrize that table and allow it to render. The page may feel a little slow until it is clustrized, but from there it will be performant again. This will provide a graceful degradation in unsupported browsers/clients. Also, the page will be easy to archive and index in search engines.

**Comment by NeXTs** [comment]
I like this idea. Will be implemented shortly.

**Comment by ibnesayeed** [comment]
That was quick! You are awesome. :)

I was also thinking if there will be a good use case where data is fetched from one place in the markup and clusterize somewhere else (or multiple places), but I don't see a compelling use case just yet, so in-place clusterization is good enough for now.
