### ISSUE TITLE
Support for offset?

### ISSUE THREAD

**Issue by babsonmatt** [NeXTs/Clusterize.js#16]
It'd be nice to be able to specify an offset to indicate where to start in the list (this would also allow someone to scroll up to previous items)

**Comment by NeXTs** [comment]
You can specify the offset by simple adding of scrollTop after initialization, clusterize will process the rest.
```javascript
var clusterize = new Clusterize({
  rows: rows,
  scrollId: 'scrollElemId',
  contentId: 'contentElemId'
});
document.getElementById('scrollElemId').scrollTop = 500;
```

I could add this as option to plugin on init and it will cost only extra 0.01kb. But I do not want to overload this simple plugin with lot of options.

**Question to community - does anybody else thinks I need to add this feature to the plugin?**
