### ISSUE TITLE
Using <a> as the base tag for each 'row' will cause clusters to not switch

### ISSUE THREAD

**Issue by vibonacci** [NeXTs/Clusterize.js#162]

**Comment by CodeJunkieio** [comment]
This is not an issues since wrapping rows with an anchor is unaccepted & non standard markup
It is expected that the table be formatted correctly and to spec in order for the plugin to behave as expected.

**Comment by vibonacci** [comment]
You are right, <a> is not allowed inside <tr> tag, which I did not realize at the time. Apologies :)
