### ISSUE TITLE
can not find

### ISSUE THREAD

**Issue by klmuralimohan** [NeXTs/Clusterize.js#165]

**Comment by klmuralimohan** [comment]
Trying to load the data using Angular 2 with clusterize js but unable to load it. here my js fiddle https://jsfiddle.net/ba5pk1dg/

Can you please provide inputs

**Comment by Thrilleratplay** [comment]
@klmuralimohan If you look at the console output in the browser's developer tools for the provided fiddle, there are multiple 404 errors.  Try loading the external libraries using resources, the same way clusterize is loaded.  This is not a clusterize.js bug.

**Comment by klmuralimohan** [comment]
ok thank you. Please find the similar thread which is created https://github.com/NeXTs/Clusterize.js/issues/166
