### ISSUE TITLE
Actually slower than without the script

### ISSUE THREAD

**Issue by benfavre** [NeXTs/Clusterize.js#17]
Didn't see anything to control the render

**Comment by NeXTs** [comment]
See #13
Clusterize don't provide data rendering, as there are a lot of tools that are really good in it: Handlebars, Mustache, Underscore templates, or even backend rendering...

You should provide data by your own as shown in [examples](http://nexts.github.io/Clusterize.js/#usage).

Although in clusterzie you able to change amount of displayed rows, see [options](http://nexts.github.io/Clusterize.js/#options) and [playground](http://nexts.github.io/Clusterize.js/#playground).

**Comment by benfavre** [comment]
I meant the scrolling is slower

**Comment by NeXTs** [comment]
I got it and issue #13 was exactly about that.

**Comment by benfavre** [comment]
My bad. Sorry for wasting your time ...

**Comment by NeXTs** [comment]
Hehe :)
It's all right, have a nice day )
