### ISSUE TITLE
Element (rows) flickering

### ISSUE THREAD

**Issue by Ladvace** [NeXTs/Clusterize.js#177]
If I scrolldown at a certain point all the element in the view start flickering

**Comment by mariorodriguespt** [comment]
I confirm this bug, on my case every time I try to scroll to the bottom I get a flicker or rows start to overlap.

**Comment by Ladvace** [comment]
I solved it and in my case was the wrong child tag

**Comment by mariorodriguespt** [comment]
Shouldn't be closed, this issue still exists.

**Comment by Ladvace** [comment]
I know but there is another one that it's the same of this
