### ISSUE TITLE
Searchable?

### ISSUE THREAD

**Issue by igorescobar** [NeXTs/Clusterize.js#19]
The only down side I've seen on the idea is that we can't use CTRL/command + F to locate something in a huge list... Any idea on how to solve this?

**Comment by NeXTs** [comment]
Implementation of search ability will double the size of plugin's sources, I'd like to keep it tiny.
If you need search - take a look at something more comprehensive, like SlickGrid
http://mleibman.github.io/SlickGrid/examples/example4-model.html

**Comment by NeXTs** [comment]
Search may be implemented separately, check "How to implement search?" [FAQ](https://clusterize.js.org/#faq)
