### ISSUE TITLE
Prepend

### ISSUE THREAD

**Issue by alexcroox** [NeXTs/Clusterize.js#20]
My div list involves inserting new rows above the rest (animated slidein and moving the rest down) yet the plugin only seems to support appending to the bottom of the list.

Would I see a performance hit if I had to insert above myself and call `update()` every time?

**Comment by NeXTs** [comment]
Hi Alex, prepend is a good idea!
I'll implement it a bit later today.

If you need this feature right now just add

```javascript
self.prepend = function(_new_rows) {
  var new_rows = isArray(_new_rows)
    ? _new_rows
    : [];
  if( ! new_rows.length) return;
  rows = new_rows.concat(rows);
  self.insertToDOM(rows, cache);
}
```

after [append function](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L100-L107), this should work fine.

**Comment by NeXTs** [comment]
[.prepend method added](https://github.com/NeXTs/Clusterize.js/commit/f6e7ade17da2a469abebf774cf079e5d8a83b42d)
