### ISSUE TITLE
Docs data/rows confusion

### ISSUE THREAD

**Issue by alexcroox** [NeXTs/Clusterize.js#21]
In your documentation the first option listed is "data", yet in your code example the option is "rows" (passing in an array called data).

Screenshot:

![http://f.cl.ly/items/402g0A2x3S1K0M3P2Y0S/Screen%20Shot%202015-05-21%20at%2009.56.50.png](http://f.cl.ly/items/402g0A2x3S1K0M3P2Y0S/Screen%20Shot%202015-05-21%20at%2009.56.50.png)

**Comment by NeXTs** [comment]
My fault. That should be called **rows**. Thank you

**Comment by alexcroox** [comment]
No worries! Such a great plugin :)
