### ISSUE TITLE
Meteor package clusterize.js

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [NeXTs/Clusterize.js#24]
Hi, Nice job! 

This is an amazing plugin and I need to use it into my meteor app, but first I have one question, when this plugin will be available on atmospherejs.com?

Thanks!

**Comment by NeXTs** [comment]
Hi!

Unfortunately I haven't worked with Meteor before. Will play with it in nearest future.
I will be grateful if someone with Meteor experience helps me with this.

**Comment by NeXTs** [comment]
Seems to be meteor has much better NPM support now
https://github.com/meteor/meteor/issues/5788
