### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by dhoko** [NeXTs/Clusterize.js#25]
Hi,

I try to test it, here is my setup: 

```html
  <!--HTML-->
  <div id="scrollArea" class="clusterize-scroll">
    <div id="contentArea" class="clusterize-content">
      <div class="clusterize-no-data">Loading data…</div>
    </div>
  </div>
```

```js
  var i = 1000;
  var data = [];
  var tmp = [];

  while(--i >= 0) {
    tmp.length = 0;
    tmp.push('<article>')
    tmp.push('<h1>Title {{id}}</h1>'.replace('{{id}}', i))
    tmp.push('<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error doloribus est commodi repellat tenetur eveniet quia nisi. Eos repellat ipsam neque veritatis aliquam voluptatem, dolorem distinctio dolore blanditiis dignissimos aperiam.</p>')
    tmp.push('</article>')
    data.push(tmp.join(''))
  }

  var clusterize = new Clusterize({
    rows: data,
    scrollId: 'scrollArea',
    contentId: 'contentArea',
    rows_in_block: 40
  });

```

```js
document.querySelectorAll('article')
NodeList[161]
```

I don't understand how to use it, onScroll nothing change. My list contains 160 article, I was thinking it would be 40. What's the problem with my setup ?

I didn't find any quick start readme.
Thanks

**Comment by NeXTs** [comment]
Your code works fine for me.
Just copy-pasted your example to jsFiddle and everything works as expected.

http://jsfiddle.net/2n1y0aj0/

**Comment by NeXTs** [comment]
Please provide your sources at jsfiddle

**Comment by dhoko** [comment]
Mea culpa, I forgot to add the CSS. With it, it works as expected O_o.

**Comment by beshur** [comment]
Hi, @NeXTs.

Was checking you fiddle, when noticed the problem that 50 elements are missing: http://take.ms/MapqT (check out the screencast)

**Comment by NeXTs** [comment]
Hi @beshur 
That fiddle uses old v0.7.1 version.
What is funny is that this bug was fixed in [v0.8.0](https://github.com/NeXTs/Clusterize.js/commit/2c937922a69454cb93a20248ed60ce62fc476e5c) :)
Better use last version v0.13.0 which was released today

**Comment by beshur** [comment]
Thanks for reply, @NeXTs.

I'm using 0.12.0 which is on cdnjs.

**Comment by NeXTs** [comment]
And problem still occurs?

**Comment by beshur** [comment]
@NeXTs, I can't notice this as have large chunks of very similar data.
Had a problem with the `rows` paraemeter, but just figured it out.

Everything's ok.
