### ISSUE TITLE
Rows as Elements instead of Strings

### ISSUE THREAD

**Issue by theluk** [NeXTs/Clusterize.js#26]
Hey,

when you use something like backbone, it is quite necessary that the backbone view has its DOM Element assigned. Otherwise this.$el end events would not work properly. 

How would a change look like, if we supported HTMLElements (not yet in dom) instead of simple strings? 
Alternatively, would it be possible to delegate this work to a "callback" for each row? Depends on what is faster. Have you had any experience with HTMLElements or callback functions?

Would be glad if you would give me some hints what I would have to adapt in the code to get it work somehow like that. would pull request it back to you if you like.

**Comment by theluk** [comment]
While adding many HTMLElements one after another might get slow, a solution could be the usage of a DocumentFragment.

    var docFragment = document.createDocumentFragment();
 
https://developer.mozilla.org/de/docs/Web/API/Document/createDocumentFragment

**Comment by NeXTs** [comment]
Hi,

why do you need to operate with DOM nodes?
If you need this to handle events - it will not work anyway as nodes would be removed from DOM while scrolling.

Much better will be to use delegation events, like that http://jsfiddle.net/q2nk4ymw/

**Comment by NeXTs** [comment]
@theluk hello there, do you still need advice regarding DOM nodes implementation?

**Comment by theluk** [comment]
Yeah that would.be realy helpful!

**Comment by NeXTs** [comment]
Well..

First of all take a look to **insertToDOM** function, it refers to **generate** function. There's nothing interesting except **this.generateEmtyRow** and **this.renderExtraTag**. Both of these function returns **row.outerHTML** so remove **.outerHTML** to keep it DOM nodes.

Go back to insertToDOM, **data.rows** contains DOM nodes, so it shouldn't **.join('')** anymore, remove that join. **this.dataChanged** won't make sense anymore so you could remove **this.options.verify_change** condition too.

**.html()** consists most of all from old IE hacks so if you don't need that - remove everything except **content_elem.innerHTML**, this should do the trick for all modern browsers.

**exploreEnvironment** function also require some changes, it's small and pretty obvious so I won't describe every line.

If you want fetch existing markup, remove **.outerHTML** form **fetchMarkup** function.

Also take a look to **self.destroy**, it's result shouldn't be **.join('')**'ed
