### ISSUE TITLE
Fullheight table with clusterize support

### ISSUE THREAD

**Issue by martinpesout** [NeXTs/Clusterize.js#32]
Is it possible to do clusterize table width height of 100% page? I see the only way how to do it? Use absolute positioning of `.clusterize-scroll` element. Is there any different workaround for this?

**Comment by NeXTs** [comment]
I suspect that you forgot to remove default max-height propert from .clusterize-scroll
Of course it could work full page.
http://jsfiddle.net/v7619xyc/

The only problem - after window resize it scrolls to top of the list, but as I promised I'll work on it in nearest days. I'll let you know.
