### ISSUE TITLE
Scrolling gets cut off in the example on Mac OS X

### ISSUE THREAD

**Issue by nilssolanki** [NeXTs/Clusterize.js#33]
On your website, if I follow the example ("Follow these easy steps to see the benefits that clusterize.js provides") up to step 4, when clusterize gets initialized, it suddenly cuts the list to 182 entries and then it stops working. Through steps 5 to 8, it stays the same way.

(The same things happends locally with a test size of 1000, it gets cut off at 350).

This happens in Firefox as well as Chrome. The examples below seem to be working fine.

![screen shot 2015-07-03 at 17 41 19](https://cloud.githubusercontent.com/assets/5477955/8501949/bfaf2dce-21aa-11e5-9b8c-0c2b27f5cf65.png)

**Comment by NeXTs** [comment]
@nilssolanki Thank you, please update to last version

**Comment by nilssolanki** [comment]
Awesome, thank you for the quick response!
