### ISSUE TITLE
How to integrate with malihu-custom-scrollbar-plugin?

### ISSUE THREAD

**Issue by mch83** [NeXTs/Clusterize.js#37]
Scrollable element does not update after load malihu-custom-scrollbar-plugin
Please help me to integrate this one with you awesome library

**Comment by NeXTs** [comment]
Hi

As malihu's plugin emulate scroll by negative margin-top, this can't be done without changing clusterize sources.
So maybe would better to use custom plugin which does not change default scroll behaviour, like [baron.js](https://github.com/Diokuz/baron)

But if you need this anyway, most important changes age

Initial markup
```html
<div id="content" class="content">
   ...
</div>
```

```javascript
// malihu plugin must be inited first
$("#content").mCustomScrollbar({
    callbacks:{
        whileScrolling:function(){
            clusterize.updatePosition(Math.abs(this.mcs.top));
        }
    }
});

//clusterize must be inited after malihu's
var data = []
for(var i = 0; i < 5000; i++) {
	data.push('<div>'+i+'</div>')
}
var clusterize = new Clusterize({
  rows: data,
  scrollId: 'mCSB_1_container',
  contentId: 'mCSB_1_container'  // this id generated by malihu's plugin
});
```

In clusterize.js sources made changes:

1.) Add updatePosition method inside constructor (after self.prepend)
```javascript
self.updatePosition = function(top) {
    self.top = top;
    scrollEv();
}
```
2.) In getClusterNum method change
```javascript
this.scroll_elem.scrollTop
to
this.top

```
