### ISSUE TITLE
Different height of rows bug

### ISSUE THREAD

**Issue by IgorBabkin** [NeXTs/Clusterize.js#41]
If height of rows not the same then appears emply space.

**Comment by IgorBabkin** [comment]
http://jsbin.com/xakuhi/edit?output

**Comment by IgorBabkin** [comment]
![screencast](https://cloud.githubusercontent.com/assets/1428790/9260906/44e8963c-4213-11e5-8c8a-c92459069513.gif)

**Comment by NeXTs** [comment]
Привет

Да, потому что в идеале строки должны быть примерно одинаковое.
Плагин-же как работает, берёт одну из строк, смотрит её высоту и умножает на кол-во строк. Так и вычисляется высота одного кластера. При незначительных колебаниях высоты строк такой эффект словить не получится. А у вас же - при инициализации мерки взялись с одной из высокой строки, а в кластере оказалось много маленьких - вот и несостыковки высоты кластера.
Такие, к сожалению, ограничения этого плагина. Высчитывать высоту каждой строки слишком затранто, так что этот вариант я отмёл.

Попробуйте указать параметр *blocks_in_cluster: 2*, кластеры должны будут заменяться чаще и до пустого места может не дойти.

```
var clusterize = new Clusterize({   
  scrollId: 'scrollArea', 
  contentId: 'contentArea',  
  blocks_in_cluster: 2    
});
```

**Comment by IgorBabkin** [comment]
Ясно. Впринципе меня все устраивает. В моей задаче будет только одна строка другого размера нежели остальные. А в этом случае все норм работает. Клевый плагин) Спс.

**Comment by IgorBabkin** [comment]
Можешь объяснить что такое кластер? Не совсем понял

**Comment by NeXTs** [comment]
Кластер это список именно тех тегов которые в данный момент находятся в DOM'e.
Но структура также включает в себя блоки, выглядит это так:

```
Кластер:
    Блок:
        тег
        тег
        тег
    Блок:
        тег
        тег
        тег
    Блок: // ←
        тег
        тег
        тег
```

Отсюда и настройки: rows_in_block, blocks_in_cluster

Когда прокручиваешь список и **скролл доходит до начала последнего блока**, кластер заменяется на следующий. Так что свойство rows_in_block лучше всего держать больше чем кол-во тегов одновременно видимых на экране. Т.е. если на экране одновременно помещается, скажем, 20 строк, rows_in_block хорошо бы указать 25+

**Comment by IgorBabkin** [comment]
а зачем нужны блоки?

**Comment by IgorBabkin** [comment]
![screencast](https://cloud.githubusercontent.com/assets/1428790/9261968/45495466-421a-11e5-9776-cfcc2c72682a.gif)

**Comment by IgorBabkin** [comment]
4.88% прыгают вверх. Я так понимаю в этот момент кластер обновляется?

**Comment by NeXTs** [comment]
Блоки на самом деле только для того чтоб определить момент когда нужно заменять на следующий кластер.
А делается это при достижении скролла самого начала последнего блока, если скролить вниз.
Теперь то я уже понимаю что можно было обойтись без этого, но когда начинал писать - так было легче думать. И так оно и осталось до сих пор..

Блоков как таковых в DOM'е нет, они только для вычислений используются.

**Comment by IgorBabkin** [comment]
это происходит при таких настройках
```javascript
  rows_in_block: 25,
  blocks_in_cluster: 4

**Comment by NeXTs** [comment]
а вот прыгать не должно. сейчас посмотрю

**Comment by IgorBabkin** [comment]
У меня пара вопросов: 
* можно ли кастомный скроллбар каким то образом прикрутить, стилизованный?
* что делать если нужно повесить обработчики событий (onclick например) на элементе списка?

**Comment by NeXTs** [comment]
* Вообще можно. Я бы посоветовал [baron.js](http://habrahabr.ru/company/2gis/blog/169359/) т.к. он оставляет дефолтное браузерное поведение (по скорости) и только стилизирует скроллбар, такой скроллер думаю можно прикрутить легче всего. Но если очень хочется использовать стилизированный плагин который сам влияет на прокрутку, типа [malihu custom scrollbar](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html), то это уже нужно менять исходники плагина, т.к. он вообще не выдаёт события scroll а имеет свою реализацию скрола через отрицательный margin. Я уже [отвечал на этот вопрос](https://github.com/NeXTs/Clusterize.js/issues/37)
* Использовать делегирование событий, смотри [faq](http://nexts.github.io/Clusterize.js/#faq)

**Comment by NeXTs** [comment]
Тебе border-spacing критично?
Из-за него несостыковки между кластерами.

```
table{border-spacing: 0;}
```

Я вот думаю, добавить в плагин стили на обнуление этого свойства или определять его и учитывать в просчетах?

**Comment by NeXTs** [comment]
А, ладно. Добавил в плагин :)
Обновляйся до 0.12.0

**Comment by IgorBabkin** [comment]
Спс большое!) Сейчас вроде все как надо работает.

**Comment by IgorBabkin** [comment]
Кстати если tr td заменить на div то вообще никаких проблем. Даже с кардинально разными высотами строк

**Comment by IgorBabkin** [comment]
http://output.jsbin.com/xakuhi/62
http://jsbin.com/xakuhi/62/edit?js,output

**Comment by IgorBabkin** [comment]
Хотя нет. Ладно думаю пора закрывать эту тему)

**Comment by IgorBabkin** [comment]
Слушай, а ты же впринципе наверно можешь понять что во вьюпорте уже 
clusterize-extra-row clusterize-bottom-space

И в этот момент наверно можно подтянуть новый кластер?

**Comment by NeXTs** [comment]
Могу, но зачем так делать? Чтоб избавится от блоков?
