### ISSUE TITLE
Clusterize removes events on ready DOM

### ISSUE THREAD

**Issue by IgorBabkin** [NeXTs/Clusterize.js#42]
![screencast](https://cloud.githubusercontent.com/assets/1428790/9262486/e1374b28-421d-11e5-8a78-b849d8c13ef6.gif)

**Comment by IgorBabkin** [comment]
http://jsbin.com/xakuhi/edit?js,console,output

**Comment by NeXTs** [comment]
События удаляются потому что все строки при инициализации переводятся в String и записываются в массив. К тому-же настоятельно не рекомендуется навешивать события на **каждый тег** при таком кол-ве строк. Это-ж какая нагрузка на браузер.
Да и зачем? Когда есть делегирование событий. 1 слушатель на все строки
см. [faq](http://nexts.github.io/Clusterize.js/#faq)

**Comment by IgorBabkin** [comment]
Да действительно. Согласен)
