### ISSUE TITLE
Improvement for Browser Limitations

### ISSUE THREAD

**Issue by dev-rke** [NeXTs/Clusterize.js#43]
As i read on http://nexts.github.io/Clusterize.js/
there are some browser limitations:

> Browsers limitations !

> Although Clusterize allows to use unlimited amount of rows all browsers have height limitations so be aware of that, use wisely and don't go crazy with it.
- Webkit/Blink 134,217,726 px
- Gecko 10,737,418 px
- Trident 17,895,697 px

I also found out, that the limitations for IE seem to be much smaller than in Firefox:

> If a DOM node is too high, browsers can not show it correctly. In FireFox, this limitation is 17895697px, in WebKit, 134217726px, both are big enough to contain tens of thousands of rows. But in IE, this limitation is as small as 1342177px. If there are 30000 rows and each row is 50px high, the browser won't be able to show it.

Source: https://github.com/oria/gridx/wiki/How-to-Create-a-Virtually-Scrolling-Gridx

So if one has 50k rows with each of a assumed height of 50px we are very fast at 2.500.000px for the whole height and we might unable to show it.

To solve this, I'd recommend to calculate a full height using top_space and bottom_space and to check if they exceed the maximum available size of around one million pixels.
If they exceed the maximum available height the calculation defines one million pixels as maximum height and uses only a percentual share of the max height for the top_space and the bottom_space.

I think about something like that:

```javascript
// line 222
var items_start = // ...
top_space = items_start * opts.item_height,
bottom_space = (rows_len - items_end) * opts.item_height,
// ...

// patch to compensate browser limitations
fullHeight = top_space + bottom_space
maxHeight = 1000000; // maximum height for IE
if(fullHeight > maxHeight) {
    top_space = Math.round(top_space / fullHeight * maxHeight);
    bottom_space = Math.round(bottom_space / fullHeight * maxHeight);
}
// end patch

// and here the normal code line 228:
if(top_space > 0) {
// ...
```

I am not sure what happens if one has more than one Clusterize Object on a single page with each around one million px height. Would they sum up? Is the height limitation a limitation of rendered dom structures (e.g. for overflow:scroll) or a limitation of the html/body element?

Do you agree with my solution or do you see any problems with this?

Thank you for developing such a great lib. :-)

**Comment by NeXTs** [comment]
Hi
Thank you for your research, this is good idea in theory, but in practice unfortunately it wouldn't work.
Long story short: because of the large scroll step that will skip clusters.
In details:

We need to know top offset to determine cluster number for current scroll position.
```
scrollEv = function() {
  if (last_cluster != (last_cluster = self.getClusterNum()))
      self.insertToDOM(rows, cache);
}

...

getClusterNum: function () {
  return Math.floor(
    this.scroll_elem.scrollTop / (this.options.cluster_height - this.options.block_height)
  ) || 0;
}
```
Decreasing height of top space will break this logic. This may be solved by adding additional scroll_coefficient variable. Let's have 1.000.000px as maximum-height constant.
```
var total_height = row_height * rows.length;
this.scroll_coefficient = Math.max(total_height / 1e+6, 1);
```
Then use it to determine correct cluster number.
```
getClusterNum: function () {
  return Math.floor(
    (
       this.scroll_elem.scrollTop / (this.options.cluster_height - this.options.block_height)
    ) / this.scroll_coefficient
  ) || 0;
}

...

top_space = items_start * opts.item_height * this.scroll_coefficient,
bottom_space = (rows_len - items_end) * opts.item_height  * this.scroll_coefficient,
```
This will allow us to correctly determine the cluster number even with changed top space.

But look what happens when we deal with huge list. For example 10.000.000 rows 50px each. That's 5e+8 px
scroll_coefficient = 5e+8 / 1e+6 = **500**!
Sensitivity of my mousewheel is pretty small, by one step it scrolls in average 50px. And it may vary.
Multiplying 50px * 500 we get **25000px for only one step of mousewheel**.
It's more than height of 2 full clusters (with default settings), which means we'll miss every second cluster by only one step of mouse wheel.
```
¯\_(ツ)_/¯
```

**Comment by dev-rke** [comment]
Thanks for your reply.
I understand your considerations.
So i think we need to extend our approach:

As i understand correct, the current implementation scrolls "natively", so each mouse scroll event scrolls as much as it is defined by the browser / operating system (e.g. 10px per event).
What do you think about emulating this behaviour? When one step natively would scroll 25000px we could interrupt the event and prevent it, instead we could manually calculate a step and define the offset.

Please consider the following pseudo code:
```javascript
$elementWithScrollbar.on('mousewheel',function(e, delta) {
  // avoid default event handling and bubbling
  e.preventDefault();
  e.stopPropagation();

  // delta should be negative when scrolling downwards
  $elementWithScrollbar.scrollTop += delta;
});
```

Using this the current scroll offset should have the size of the mousewheel delta and there should be no other problems.

What do you think?

> ``` ¯\_(ツ)_/¯ ```
 

Btw.: I like this smiley :-)

**Comment by NeXTs** [comment]
Well, emulating scroll behaviour will bring a lot of headaches in trying to make the same behavior in all browsers. You know.
For example all known [jquery.mousewheel](https://github.com/jquery/jquery-mousewheel/blob/master/jquery.mousewheel.js) plugin consist almost of 200 lines of code without comments, which would almost double the size of clusterize.js. Despite mouse wheel we have to consider also scroll bar dragging, mobile touch events, etc...
I am sorry but I think that it's not worth the effort. Native scroll event covers all possible cases.
I'd like to keep it simple.

JFF made demo with 10m rows. 1 mousewheel step affetc few clusters. Craziness :)
https://jsfiddle.net/nexts/mc756rtL/

**Comment by dev-rke** [comment]
Ok, sorry, i didn't know about the evolution of the mousewheel handling, code if jquery.mousewheel seems to handle very very deprecated events in very very old browsers. :D 
You are right, we should stop here and close the issue, it was just an idea to improve browser limitations, but if we are ending up on fixing several browser limitations in several browsers there is no win-win situation.
And if one will process such huge data structures in the browser one might better go with an in-browser database implementation and give the user the ability to query a local data store.

But i am still impressed that handling of 10m rows in the browser is possible - and also fast! :-)
