### ISSUE TITLE
Pagination on scroll end for REST services

### ISSUE THREAD

**Issue by dev-rke** [NeXTs/Clusterize.js#44]
I just thought about if it might be possible to define an event before further
data will be appended e.g. using ajax like for paginated data.

E.g. you load page one from a REST service and want to load additional pages when the user scrolls down to the end and before he reaches the end further data will be loaded.

Pseudocode:
```javascript
// user defined setting
options.percentageScrollOffsetBeforeLoadData = 0.95;

// clusterize
if(options.loadDataCallback()) {
  $elementWithScrollbar.on('scroll',function(e) {
    percentageScrollOffset = $(this).scrollTop / totalheight;
    if(percentageScrollOffset > options.percentageScrollOffsetBeforeLoadData) {
      options.loadDataCallback()
    }
  });
}
```

This would enable the user to handle additional page loads without manually 
injecting in the event handling of clusterize.

**Comment by NeXTs** [comment]
Hi, this is good idea.
In the nearest future I will implement list of callbacks and events for most useful needs. Probably I'll consider this case too.

**Questions to developers**: do you need this feature? Should I increase the plugin's size by this functionality ?

**Comment by dev-rke** [comment]
If you want to keep it small, it might also be a good alternative just to expose some hooks where one can enhance the functionality with a custom implementation.

Another alternative might be to split the functionality in two modules: a very small core module and an extended feature module, which hooks into the core.

**Comment by sergeyourkiv** [comment]
Yep, it's worth of it

**Comment by Abhinav1217** [comment]
I would like to not increase the size of the plugin for this feature. But to expose some callback hooks which can be used to extend core plugin with all the extra functionalities including this.

**Comment by NeXTs** [comment]
Now you able to subscribe to update scroll position via scrollingProgress callback. Or get progress position directly via calling getScrollProgress method.

```
var clusterize = new Clusterize({
  rows: data,
  scrollId: 'scrollArea',
  contentId: 'contentArea',
  callbacks: {
    scrollingProgress: function(progress) {
      if( progress > 80 ) {
        // do stuff
      }
    }
  }
});

// or call it directly
console.log(clusterize.getScrollProgress());
```

**Comment by Abhinav1217** [comment]
Will try this today. Thanks.

**Comment by dev-rke** [comment]
Great! Thank you! :-)
