### ISSUE TITLE
How to determine if row element is in view (port)?

### ISSUE THREAD

**Issue by s-a** [NeXTs/Clusterize.js#45]
I try to implement an active row cursor on key up and down. For this reason I want to return false in key down to prevent scrolling when the next / previous item is already in view. 

I have tried this, but I am missing something here... The algo stumbles on clusterized offset.
```javascript
View.prototype.isInView = function($elem) {
	var id = "scrollArea" + this.id;
	var $scrollArea = $('#' + id);

	var docViewTop = $scrollArea.scrollTop();
	var docViewBottom = docViewTop + $scrollArea.height();
	var elemTop = $elem.offset().top;
	var elemBottom = elemTop + $elem.height();
	return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
};
```

Can you tell me what I am doing wrong here?

**Comment by NeXTs** [comment]
```
var elemTop = $elem.offset().top + docViewTop;
```
Next time add jsfiddle example please.

**Comment by s-a** [comment]
Allright :+1: Ty for your fast help.
