### ISSUE TITLE
Does it works with React?

### ISSUE THREAD

**Issue by edravis** [NeXTs/Clusterize.js#49]
I'm currently trying to implement it with React but it doesn't work.

I've tried a bunch of implementations and normally doesn't happen, at all. Just render as always.

Then I try:
```
var clusterize = new Clusterize({
      rows: data,
      scrollId: 'scrollArea',
      contentId: 'contentArea'
    })
```

Where `data` were my custom `ReactElements` and I get the following error:
`Uncaught TypeError: Cannot read property 'tagName' of undefined`

on 

https://github.com/NeXTs/Clusterize.js/blob/5b4ac699b1924ac8a562170d8b1900ae5025a54a/clusterize.js#L173

I don't if it helps, maybe I'm just trying something impossible or doing it totally wrong. Any help is welcomed!

**Comment by NeXTs** [comment]
Hi Rubén!
I am sorry but I haven't had experience with react yet so I couldn't help you with this at this moment. I saw there was implementation of Clusterize.js at react, that seems to be still in process but take a look anyway.
https://github.com/freakycue/react-clusterize

**Comment by ayrton** [comment]
I'm currently working on a react library called [`react-cluster`](https://github.com/ayrton/react-cluster) greatly inspired by this plugin, I'll be publishing the first release later this week. Any feedback on the library would of course be greatly appreciated @NeXTs :smile:

**Comment by NeXTs** [comment]
Glad to hear that! I'll take a look later :)
11 февр. 2016 г. 18:38 пользователь "Ayrton De Craene" <
notifications@github.com> написал:

**Comment by OrzX** [comment]
> I'm currently working on a react library called [`react-cluster`](https://github.com/ayrton/react-cluster) greatly inspired by this plugin, I'll be publishing the first release later this week. Any feedback on the library would of course be greatly appreciated @NeXTs 😄

Your implement does't work well, still create too much DOM elements. Can you improve it?

**Comment by vgvinay2** [comment]
still create too much DOM elements. Can you improve it?
