### ISSUE TITLE
Render issues while scrolling 0.5M rows in Firefox 41.0.1 / Ubuntu 12.04

### ISSUE THREAD

**Issue by sergeyourkiv** [NeXTs/Clusterize.js#50]
While scrolling large table, it shows grey screen or black lines or some other contorted picture, sometimes changing left and right part of table. After about 5 seconds after stopped scrolling it shows real picture. It doesn't seem to be smoothly. Hope bug can be found and fixed. Lib is really awesome. 
![screenshot from 2015-10-13 21 42 27](https://cloud.githubusercontent.com/assets/8556402/10465021/69e57df8-71f5-11e5-9313-d2a460651ab2.png)
![screenshot from 2015-10-13 21 43 14](https://cloud.githubusercontent.com/assets/8556402/10465022/69facec4-71f5-11e5-892f-370a27570439.png)

**Comment by NeXTs** [comment]
Seems you have reached browser limitations that were [mentioned here](http://nexts.github.io/Clusterize.js/#browsers_limit) and there's nothing I can do to fix it so far. Sorry
```
¯\_(ツ)_/¯
```

**Comment by sergeyourkiv** [comment]
:)
