### ISSUE TITLE
Wrong cell width with fixed table

### ISSUE THREAD

**Issue by jbanety** [NeXTs/Clusterize.js#53]
Hi,

My table is rendered with a fixed layout.
My cells are all sized with a specific width.

When I scroll down, Clusterize creates the "top-space" row which is an empty tr.
So my browser cannot set the fixed width (the width comes from the first displayed row). 

Here is the example : http://jsfiddle.net/kx9fa0se/9/

**Comment by NeXTs** [comment]
Hi
Good catch! Thanks for repothing this issue. I will investigate

**Comment by NeXTs** [comment]
as a quick workaround duplicate thead section into table with content
http://jsfiddle.net/kx9fa0se/10/

**Comment by jbanety** [comment]
I didn't think about it.
I added several td to the "top-space" tr when "clusterChanged" event triggers.
Your workaround is better.

**Comment by NeXTs** [comment]
> I added several td to the "top-space" tr when "clusterChanged" event triggers.

:D
![brutal](http://img-comment-fun.9cache.com/media/aWOg8MZ/ajQ0n3ld_700w_0.jpg)

**Comment by jbanety** [comment]
Yes It's a bit hacky but It does it !

**Comment by jbanety** [comment]
This workaround breaks the "no data" row which needs a colspan to be as larger as the entire table.

**Comment by NeXTs** [comment]
@jbanety sad to hear that
Since you've already forked project, add extra line [here] (https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L212) temporarily
```
td = document.createElement('td');
td.colSpan = 100;
```
This will force **td** to be full width. I'll think about better solution

**Comment by vamp** [comment]
@NeXTs, better would be to add some callback, e.g. generateEmptyRow and pass created element to it:
```
var callbacks = options.callbacks;
callbacks.generateEmptyRow && callbacks.generateEmptyRow(empty_row);
```

**Comment by NeXTs** [comment]
I'm planning to rethink clusterize structure and instead of additional tags, use paddings/margins

**Comment by Carmezim** [comment]
@NeXTs when scrolling through a list of `<div>`s, `top-space` row creates a huge white empty space. Is there a way to prevent this?

**Comment by NeXTs** [comment]
Have some demo?

**Comment by Carmezim** [comment]
Not a demo but hope this ss can help give some clarity
![image](https://user-images.githubusercontent.com/16518410/28284712-dcb4a49c-6b29-11e7-95cb-9ad96dd2b660.png)

**Comment by NeXTs** [comment]
> Have you seen this before?

No. I can check this but I need demo
