### ISSUE TITLE
Scroll to specific item in list

### ISSUE THREAD

**Issue by OscarGodson** [NeXTs/Clusterize.js#55]
I have a map up top and a table below. The table rows below link to a marker on the map. I want to make this bidirectional. So if you click on a marker it selects a in clusterize and marks it selected. The issue I'm running into is how do I scroll to elements that dont exist yet. Is there a trick to figuring out where a row will be so I know what to `scrollTo()`?

I haven't tried it yet but the only other idea I had was to remove height restriction, find the offset of the element, reapply the height, then scrollTo.

**Comment by NeXTs** [comment]
This is interesting question, Oscar.

Does your rows have same height?

**Comment by OscarGodson** [comment]
Its user set, so each cell/row could be totally different heights :\

**Comment by NeXTs** [comment]
Nope, rows_in_block can not be changed dynamically, by design. But you are free to extend library as you wish.
At the moment, you can achieve the same result by:
* calling `clusterize.destroy(true)` which will insert all rows to the DOM
* find your row's position
* re-`init` clusterize
* scroll to row by `document.getElementById('scrollElemId').scrollTop = 500;`

See [playground](https://clusterize.js.org#playground) *Destroy table* section and click "Inserts all rows to the table" button which demonstrates such behaviour, then click "Init clusterize" button

**Comment by OscarGodson** [comment]
Hmm, im messing with it, but I can't seem to remove the scroll event. I call destroy on the table and all the nodes are in the DOM (which you can see Chrome maxing out in the inspector), but the event listener stays around. When I scroll the page locks up and all of a sudden clusterize is flipped back on.

![](https://cloud.githubusercontent.com/assets/20615/11229248/70004326-8d48-11e5-8eba-92891f8ab917.png)

**Comment by OscarGodson** [comment]
Sorry, figured it out.

**Comment by OscarGodson** [comment]
```js
clusterize.destroy();
var $scrollToElement = $('[data-id="' + id + '"]');
var scrollToPosition = $scrollToElement.offset().top - $scrollToElement.parent().offset().top;

var clusterize = new Clusterize({...})
document.getElementById('scrollArea').scrollTop = scrollToPosition;
```

This almost works. The only issue is I think Clusterize is altering the height or something. If I scroll to an element within the available DOM the above works. If it's not in the DOM the scroll position is off. If I remove the reinit code it scrolls to the element perfectly. 

I can _kind of_ hack it by doing this code twice and in a timeout (timeout because sometimes its not rendered yet after enabling the clusterize again, maybe because of the debounce?). So after the scrollTop in my code example above I do this:

```js
    setTimeout(function () {
      var $scrollToElement = $('[data-id="' + id + '"]');
      var scrollToPosition = $scrollToElement.offset().top - $scrollToElement.parent().offset().top;
      document.getElementById('scrollArea').scrollTop = scrollToPosition;
    }, 10)
```

That gets it almost perfect but this requires double height calculations and still not perfectly lined up. Also the code is super janky :P any other suggestions welcome.

My next attempt I'm going to scroll in chunks of 100px, check if the element exists, and keep scrolling until the element is found and see which is faster and more accurate.

**Comment by OscarGodson** [comment]
Dang, I'm just not getting it. I've tried every hacky way I can think of. My final theory was to do the scrolling but it doesn't work because sometimes when I do scrollTop it gets "stuck" with an empty row up top and thus causing an infinite loop since it can never scroll higher. Like these two are both times I tried to scroll up to 20:

![map of top 100 websites worldwide 2015-11-18 13-55-23](https://cloud.githubusercontent.com/assets/20615/11255651/3e153222-8dfc-11e5-9630-222e652dd8a7.png)
![map of top 100 websites worldwide 2015-11-18 13-57-11](https://cloud.githubusercontent.com/assets/20615/11255657/45a4be90-8dfc-11e5-860a-56099eab47e0.png)

And scrolling down never quite hits the mark. Again, tried to go to row 20.

![map of top 100 websites worldwide 2015-11-18 13-57-37](https://cloud.githubusercontent.com/assets/20615/11255669/564c55c8-8dfc-11e5-9f26-62f318b274ee.png)

I've tried different speeds (as fast as 10ms, and weird numbers like 997ms) and also tried offsetting the first/last element offsets by like 100px or other numbers. It always gets stuck or is off.

Here's a demo of the behavior: http://jsbin.com/qibihah/edit?css,js,output

Try scrolling to the bottom (item 99) then type in 40. For me I get stuck on item 81 and it never scrolls higher. From the top go to 50. 50 is scrolled past view and you can't see it. In the JSBin example I included a way to log out the events happening so you can see whats happening in the loop

**Comment by NeXTs** [comment]
@OscarGodson 
It's still little jumpy but as a concept should be fine :)
http://codepen.io/NeXTs/pen/VvRyJE?editors=101

**Comment by NeXTs** [comment]
@OscarGodson So how it's going?
This helped to solve your task?

**Comment by OscarGodson** [comment]
Unfortunately, no. I'm still not entirely sure how to fix it yet. Your example still breaks if you make the content more than 1 line each. Here's some examples:

99 goes to 137
![a pen by denis 2015-12-02 15-25-24](https://cloud.githubusercontent.com/assets/20615/11547476/0fac009c-9909-11e5-9703-7fee019f9aba.png)

125 went to 109/110
![a pen by denis 2015-12-02 15-27-16](https://cloud.githubusercontent.com/assets/20615/11547489/31490862-9909-11e5-82a3-e3e9d75babf0.png)

**Comment by OscarGodson** [comment]
It might be next to impossible actually. I noticed sometimes there's these giant jumps between blocks. Like in this table I'm at 21:
![map of top 100 websites worldwide 2015-12-02 16-07-16](https://cloud.githubusercontent.com/assets/20615/11548210/ebf6ef26-990e-11e5-84a1-2eb9ebf7a21d.png)

Then I scroll up like 2px and...
![map of top 100 websites worldwide 2015-12-02 16-08-57](https://cloud.githubusercontent.com/assets/20615/11548220/03099574-990f-11e5-9f87-b6dcc954544e.png)

**Comment by vamp** [comment]
@OscarGodson, try to use clusterize.js properly (main requirement - same height of each row in table)

**Comment by NeXTs** [comment]
@OscarGodson 
Wow, [those](https://cloud.githubusercontent.com/assets/20615/11548220/03099574-990f-11e5-9f87-b6dcc954544e.png) rows height vary too much. Margin of error in the row height may be about 50% - 150% while your rows height varies up to 400% times which leads to false miscalculations of overall cluster height.

> Your example still breaks if you make the content more than 1 line each

I'll investigate it in my spare time

**Comment by OscarGodson** [comment]
I went ahead and added `white-space: nowrap`. It doesn't really make it readable for some longer lines but scrolling to a specific line works. _Most_ content isn't longer than an address so it'll do for now. After forcing it to one line with that CSS my "scrollToRow" method is just this

```js
$('#scrollArea').scrollTop($(this.container).find('[data-id]').height() * id);
```

**Comment by aschilling** [comment]
I would be very much interessted in a solution as well. In particular, I have the problem that the divs I use with clusterize are by default different sizes, such that I cannot use the suggested solutions to scroll to the particular div.
