### ISSUE TITLE
Load Clusterize using node.js

### ISSUE THREAD

**Issue by TheColorRed** [NeXTs/Clusterize.js#56]
How do you use this within node.js (Specifically electron for desktop applications)?

When I try this I get an error:

    require('clusterize.js');
    var clusterize = new Clusterize({
        rows: data,
        scrollId: 'scrollArea',
        contentId: 'contentArea'
    });

> Clusterize is not defined

**Comment by NeXTs** [comment]
Install it via npm 
```
npm i clusterize.js
```

And use commonJS syntax
```
var Clusterize = require('Clusterize');
```

**Comment by TheColorRed** [comment]
How would you then pass the 2 required options to it?

**Comment by NeXTs** [comment]
```
var Clusterize = require('Clusterize');

var clusterize = new Clusterize({
    rows: data,
    scrollId: 'scrollArea',
    contentId: 'contentArea'
});
```

**Comment by TheColorRed** [comment]
Alright thanks! I'll give that a try!

**Comment by NeXTs** [comment]
To be honest, I never ran Clusterize.js on the node.js as it's browser-oriented library in general.

Module support was implemented for module loaders like require.js, browserify which support amd and commonjs specifications on the client side.

What you trying to achieve by running Clusterize.js on backend side?

**Comment by TheColorRed** [comment]
I am actually running it using Electron which is to make desktop applications:

> Build cross platform desktop apps with web technologies

http://electron.atom.io/

Electron uses webkit to display the content of the window which is written with HTML/CSS/JavaScript. You can then leverage node to do node related tasks.

So I am making a database manager (Similar to mysql workbench, dbBever, HeidiSQL, etc.)

**Comment by NeXTs** [comment]
Cool :+1:
