### ISSUE TITLE
Rows not displayed for 500,000 records on MS Edge

### ISSUE THREAD

**Issue by ritcoder** [NeXTs/Clusterize.js#59]
Just testing the library from the url [here](https://clusterize.js.org/?utm_source=jquer.in&utm_medium=website&utm_campaign=content-curation).

Started with MS Edge (v 25.10586.00). When it has 500,000 records and I scroll to the end, nothing is displayed. Tested the same thing in chrome and it worked.

The recordIt video [here](http://recordit.co/c1mCvPAxDY)

**Comment by NeXTs** [comment]
Hi there
Yep, that's known issue, take a look at "[Browsers limitations](https://clusterize.js.org/#browsers_limit)"
Anyway, thanks for report
