### ISSUE TITLE
Function to build on the fly

### ISSUE THREAD

**Issue by OscarGodson** [NeXTs/Clusterize.js#61]
Clusterize handles scrolling very well, but a huge issue for us is initial load because for big datasets we have to build a string with tens of thousands of rows which locks up browsers and sometimes crashes it. Looks something like

```js
var buildRows = function () {
    var tableData = [];

    rows.forEach(function (row, rowIndex) {
      var rowHtml = '<tr data-id="' + row.id + '">';

      row.data.forEach(function (cell, cellIndex) {
        rowHtml += '<td data-position="' + cellIndex + '">' + cell + '</td>';
      });

      rowHtml += '</tr>'
      tableData.push(rowHtml);
    });

    return tableData;
}
```

We also tried doing the above in "threads" with setTimeouts but what happens is each time we injected it into Clusterize it locked up because it had to build the rows _and_ Clusterize had to re-render. 

Is there a hook somehow to have Clusterize do the above on the fly when you build the DOM or if not, do you have any other suggestions on this?

**Comment by NeXTs** [comment]
Hi Oscar

Please provide any simplified demo at codepen, this may help a lot for investigation.
As quick suggestion workaround.. how about:

1. Init clusterize
2. Build and insert rows to fill first cluster, let's say 100 rows so user will be able to see something in the list
3. Maybe display some loading indicator at the bottom of the list (I'd made ​​it via pseudo-element)
4. Meanwhile in background build all remaining rows in 'threads' with setTimeout, but not inject
5. When all rows are build - inject it to the list at once

I'll think about better solution.

**Comment by NeXTs** [comment]
@OscarGodson hi, how it's going?

**Comment by OscarGodson** [comment]
We ended up use Web Workers which helped but is a bit more complicated. The solution of loading the first chunk then others would have required a lot of works on other things to know if it's in a loading state or not (like our search, sorting, etc). Web Workers at least sped it up by passing off the string creation to a new thread

**Comment by NeXTs** [comment]
@OscarGodson 
Try this version http://codepen.io/NeXTs/pen/vGGvRb
Also set option `verify_change: true`

**Comment by NeXTs** [comment]
@OscarGodson hey, I'm waiting for your feedback :)

**Comment by OscarGodson** [comment]
thanks, ill try to readd it and see how it works. Might be a little hard since it was all refactored to work with workers (sends the data async with events, etc) but I'll give it a shot

**Comment by OscarGodson** [comment]
It appears to work! I think this + the workers would actually be a great hybrid because it'll speed up the workers even more. I need to do more speed tests but the initial feel seems like it renders rows faster than before.

**Comment by NeXTs** [comment]
`verify_change` option was removed.
It's now permanently enabled.
