### ISSUE TITLE
Events are not attached

### ISSUE THREAD

**Issue by farshid1** [NeXTs/Clusterize.js#65]
I am using riot.js to build my UIs. One of my UIs is a table that shows around 2000 elements so clusterize seems to be the perfect solution. The problem is that my events on my table rows are not triggered anymore. Without using clusterize the events are working fine. Any help would be greatly appreciated.

**Comment by NeXTs** [comment]
Hi
Events should not be attached to every row.
They should be attached using event delegation. Check question 3 from [FAQ](https://clusterize.js.org#faq)

**Comment by farshid1** [comment]
I appreciate your fast response. Sorry I must have missed that. Initially I thought one of the reasons my app is very slow is because I have attached an event handler to each of my row elements. After applying your solution, I did not see much of improvement. The thing is that each of my rows wraps a lot of DOM elements and I render all of the rows at the same time (I'm getting the data through AJAX and update an array which I then loop through). I was thinking of using setTimeout to slowly get the data from the server. Does the uodate function helps with this performance issue?

**Comment by NeXTs** [comment]
Some code sample at codepen would be helpful.

I don't really get what exactly kind of performance issues do you have.
If you get a lot of rows (say tens of thousands) from server and render them in one loop - page may be unresponsive while generating rows in loop. For this case obvious solution will be separate received array of data from server and generate those separated chunks successively inside setTimeout(fn, 0) calls. After each chunk done you could call something like clusterize.append(new_chunk) to append new rows to the list.

**Comment by NeXTs** [comment]
Closing due inactivity
