### ISSUE TITLE
clusterize with masonry/packery/isotope can be imaginable ?

### ISSUE THREAD

**Issue by stephanedemotte** [NeXTs/Clusterize.js#66]
I have a lot of data, but not per row, i use packery.js for a nice display.

Do you think i can make it work with clusterize.js ?

thanks !

**Comment by NeXTs** [comment]
Hi Stephane

Nope, items in those plugins are absolute-positioned.

Same "show/hide" technique of course may be applyed there too, but not with current Clusterize implementation

**Comment by stephanedemotte** [comment]
i have try :)

Thanks a lot !
