### ISSUE TITLE
Dynamically Adding Table Rows Completely breaks scrolling after a certain point

### ISSUE THREAD

**Issue by chernj** [NeXTs/Clusterize.js#69]
http://tinypic.com/r/34t31n6/9

As seen here scrolling becomes very screwy after a certain point (in this scenario I think it is when the 10th row tries to go offscreen, snapping it back at the bottom)

I've tried many things, such as using update vs append and forcing a refresh on every addition (which I've scheduled to happen at most every second), and the only influence I have over this is by changing rows_in_block and blocks_in_cluster, which only changes at what row this breaking happens (for example, using rows_in_block: 30 and blocks_in_cluster: 16 I get this breaking at 310)

**Comment by NeXTs** [comment]
Share with me properties which you pass to clusterize on initialization.
Or much better would be if you provide example at codepen/jsfiddle

**Comment by NeXTs** [comment]
How it's going?
