### ISSUE TITLE
Issue in Implementation

### ISSUE THREAD

**Issue by LamaBimal** [NeXTs/Clusterize.js#74]
Hello NeXTs, i have used clusterize.js for displaying large amount of data, but my table contains rowspan too. and it is not working with it. How could i maintain it?

**Comment by NeXTs** [comment]
Please specify more details what exactly does not work, with code example at codepen
It works as expected for me

http://codepen.io/NeXTs/pen/jApprm

**Comment by LamaBimal** [comment]
I got my answer NexTs, that I am using the rows_in_blocks as 2 and blocks_in_cluster 2, in this i got the unexpected results. Thanx for ur reply.

**Comment by LamaBimal** [comment]
Hello NexTs, i have one questions with implementation with angularjs.Can we use it with alternative way , without using custom directives. I have minimun 50 different structured tables, and i think it is not better way to make directive for each tables.

**Comment by NeXTs** [comment]
@LamaBimal I am not big expert of AngularJS
Maybe @Thrilleratplay may help you

**Comment by Thrilleratplay** [comment]
@LamaBimal The only advice I can give is to abstract out the directives as best as possible and reuse them where ever you can.  

Additionally, I am trying to assemble some [functional examples of using Clusterize.js with Angular.js](https://github.com/Thrilleratplay/Angular-Clusterize-Examples) which may helpful.

**Comment by LamaBimal** [comment]
Thanx @Thrilleratplay  and @NeXTs

**Comment by NeXTs** [comment]
Clusterize doesn't even know about thead, it's up to you how handle thead.

**Comment by LamaBimal** [comment]
Hello NexTs, I got 1 issue, while changing the cluster, for the highest value of rowspan it doesnot work

**Comment by NeXTs** [comment]
@LamaBimal Could you provide an example?

**Comment by LamaBimal** [comment]
hello NexTs, just provide two values rows_in_block:5,
  blocks_in_cluster:2 in a example http://codepen.io/NeXTs/pen/jApprm and just scroll it u'll got it at 6th row. I have same case in my scenario for large data sets.

**Comment by NeXTs** [comment]
Okay let's admit it, clusterize just doesn't play well with rowspan's
This happens because upper row which may contain rowspan attribute - isn't in DOM so that rowspan rule is missed and that's why lower rows moved out.

Take it as a disadvantage of using virtual scrolling

If all your rows have same height and rowspan attributes specified at predictable rows order - you could predict necessary cluster height and set `rows_in_block` and `block_in_cluster` so that rows with colspan rule were in DOM for every cluster. For [this example](http://codepen.io/NeXTs/pen/VjGbwr) `rows_in_block: 3, blocks_in_cluster: 4` works well

**Comment by LamaBimal** [comment]
Hello NexT's, rowspan is unpredictable, so, how could i maintain single cluster for whole records and number of records are also unpredictable.

**Comment by LamaBimal** [comment]
Hello NexT's how could we implement object destroy function in clusterize?

**Comment by NeXTs** [comment]
@LamaBimal Hey there

Have you looked at docs?
There are `.destroy()` method which may be called as `clusterize.destroy()` where `clusterize` is instance of `Clusterize` object

**Comment by LamaBimal** [comment]
Ya @NeXTs , i have looked the docs, but i am confusing where could i place it.

**Comment by NeXTs** [comment]
Hey there

Did you read docs? There are .destroy method

Call it like clusterize.destroy() where clusterize is instance of
Clusterize object

четверг, 4 августа 2016 г. пользователь Bimal написал:
