### ISSUE TITLE
IE11 does not display all 500k lines in the demo 

### ISSUE THREAD

**Issue by fantastik78** [NeXTs/Clusterize.js#76]
Hi,

I tried your demo page on Internet Explorer 11 and on step 7-8 not all 500k lines are displayed.
It stops on the 290 342 row (on two different laptops).

Is it a known bug ? Does IE has some sort of limitation ?

PS: I tried another lib that seems to have the same kind of behavior (angular-vs-repeat)

**Comment by NeXTs** [comment]
Hi,

yep, it's noted in "Browsers Limitations" section, checkout [this link out](https://clusterize.js.org#browsers_limit)

**Comment by fantastik78** [comment]
So the value for Trident (17,895,697 px) is the maximum height of the scrollable div ?

**Comment by NeXTs** [comment]
Well, I got this info from [this thread](https://github.com/NeXTs/Clusterize.js/issues/12#issue-72956278) but seems to be it's correct

**Comment by NeXTs** [comment]
Also, there [was discussion](https://github.com/NeXTs/Clusterize.js/issues/43#issue-102579981) regarding how to fix this, but without success

**Comment by fantastik78** [comment]
Arrff, I will have to find another solution that suits our PO :)
Big thanks, and awesome reactivity!
Nice lib :+1:
