### ISSUE TITLE
Dynamically adding rows as nodes should be allowed

### ISSUE THREAD

**Issue by alexandrubau** [NeXTs/Clusterize.js#81]
I'm unable to add rows as following: `clusterize.append([$('<div>')])`

The only way to get around this is to use another element as a wrapper, and then extract the child node using __.html()__. Example: `clusterize.append([$('<div>').append($('#item-of-interest').clone()).html()])`

**Comment by NeXTs** [comment]
It's not the only option, you could use native **.outerHTML**

`clusterize.append([$('<div>').get(0).outerHTML)`

**Comment by alexandrubau** [comment]
@NeXTs thank you for your suggestion.
