### ISSUE TITLE
When scrolling in table, new lines don't always load for display

### ISSUE THREAD

**Issue by bharatode** [NeXTs/Clusterize.js#82]
rows_in_block: 10,
blocks_in_cluster: 4,

600+ lines and they try to scroll , not all lines will display on the screen.  It seems that when you scroll through 40 lines, the next 40 should show up but they don't so you will only see a couple of lines left on the screen even though there are many remaining.

**Comment by NeXTs** [comment]
Can't reproduce this problem
http://codepen.io/NeXTs/pen/KgdKgJ

Please provide example at codepen

**Comment by bharatode** [comment]
It's working fine in desktop, but when i tried to touch screen monitor then still i am facing that issue.

**Comment by NeXTs** [comment]
Do you mean at mobile device?

**Comment by NeXTs** [comment]
Could you please make a video of that issue?
It would be much easier to determine problem

**Comment by bharatode** [comment]
can you give me your email id so i can send you teamviewer file( .tvs)?

**Comment by NeXTs** [comment]
youCanCallMeDen@gmail.com

**Comment by bharatode** [comment]
I sent you mail with attachement.

**Comment by NeXTs** [comment]
I see.
interesting, what's height of rows?

**Comment by bharatode** [comment]
It's developed in angularjs application.
   angular.module('packing')
    .directive('clusterize', function ($timeout, $compile) {
        return {

            restrict: 'E',
            template:
                '<table id="tblPackListThead" class="table table-striped table-fixed" ng-if="vm.packList">' +
                    '<thead>' +
                        '<tr>' +
                            '<th class="col-sm-1">Item&nbsp;#</th>' +
                            '<th class="col-sm-1 text-center">Line&nbsp;#</th>' +
                            '<th class="col-sm-4">Item Description</th>' +
                            '<th class="col-sm-1 text-center">Pack</th>' +
                            '<th class="col-sm-1 text-center">Make</th>' +
                            '<th class="col-sm-1 text-center">Order</th>' +
                            '<th class="col-sm-1 text-center">Pack</th>' +
                            '<th class="col-sm-1 text-center">Remain</th>' +
                            '<th class="col-sm-1"></th>' +
                        '</tr>' +
                    '</thead>' +
                '</table>' +
                '<div id="packingScrollArea" class="clusterize-scroll">' +
                    '<table id="tblPackList" class="table">' +
                        '<tbody id="contentArea" class="clusterize-content">' +
                            '<tr class="clusterize-no-data">' +
                                '<td colspan="9">Loading data…</td>' +
                            '</tr>' +
                        '</tbody>' +
                    '</table>' +
                '</div>',

            link: function ($scope, elem, attr, ctrl) {
                // init clusterize
                var clusterize = new Clusterize({
                    rows: $scope.rows,
                    scrollId: 'packingScrollArea',
                    contentId: 'contentArea',
                    rows_in_block: 10,
                    blocks_in_cluster: 4,

                });

                clusterize.html = function (data) {
                    var content_elem = angular.element(this.content_elem);
                    content_elem.html(data);
                    $compile(content_elem.contents())($scope);
                };

                $scope.$watch('rows', function () {
                    // watch for changes and update
                    clusterize.update($scope.rows);
                });
            }
        }
    });

**Comment by bharatode** [comment]
Used below css class in css for height.

.clusterize-scroll{
  max-height: 557px;
   min-height: 557px;
  overflow: auto;
}

**Comment by NeXTs** [comment]
what's height of single row? not whole scrollable container

**Comment by bharatode** [comment]
56px

**Comment by NeXTs** [comment]
Hello @bharatode 

I am sorry but I am not an expert in Angular.js
I see you've redefined `.html` function and unfortunately I can not predict if it may affects plugin's inner logic.

Did you saw fantastic clusterize.js + angular.js examples made by Tom Hiller?
https://github.com/Thrilleratplay/Angular-Clusterize-Examples

**Comment by Thrilleratplay** [comment]
@bharatode  

As I do not do any mobile development myself, It did not occur to me to test mobile devices.  I'll do that later today.

Looking at the directive you posted, it doesn't look like you do any lazy loading.  So if you are all 600+ lines initially, I don't know why it wouldn't render the next cluster.  The only thing I can think of is to do some more debugging with the scrollingProgress, clusterWillChange and clusterChanged callbacks to get a better idea of what Clusterize.js is doing when the cluster should change.
