### ISSUE TITLE
handle same data, clusterChanged  was invoked more than one time

### ISSUE THREAD

**Issue by aeolusheath** [NeXTs/Clusterize.js#84]
as a result , page will reload same data many times with content flickering in the scrollContainer . 

anyone help?

**Comment by NeXTs** [comment]
hi

could you please provide an example at codepen?

**Comment by NeXTs** [comment]
Sorry mate, I can't reproduce
http://codepen.io/NeXTs/pen/EgXXoP?editors=1010

Which version do you use?

Make sure you are using at least v0.16.0, there was related fix. Of corse better would be to use latest v0.17.1

**Comment by aeolusheath** [comment]
@NeXTs  bro,sorry I cann't give u all the code. becuase the data is so large . and I use vue .

you can see this codes:  

log has a  watch function ,when log change ,update  cluster
```javascript
    watch: {
      'logs': function(val) {
        clusterizeobj.update(val)
      }
    },
```

```javascript
   clusterizeobj=new Clusterize({
        rows: data,
        scrollId : 'ScrollContainer',
        contentId : 'LogContainer',
        callbacks : {
          clusterChanged:  ()=> {
            console.log('invoked time', moment(new Date()).format('HH:mm:ss'), new Date().getTime())
          }
        }
      })
```

the log picture:



![image](https://cloud.githubusercontent.com/assets/5978548/18906732/537df8dc-859b-11e6-8c39-4f480525638b.png)

**Comment by NeXTs** [comment]
well, such behaviour may be caused by using it in pair with vue :\

I am not familiar with vue and I don't know which impact it has on DOM

**Comment by aeolusheath** [comment]
if clusterizeobj.update(val)  this function execute successfully,  is there some conditions?

**Comment by aeolusheath** [comment]
@NeXTs  you can use large data . every single item string 's length is more than 20 0r 30 or 40  。。maybe it occurs

**Comment by NeXTs** [comment]
I think would be better if you ask this guy
https://github.com/vue-comps/vue-clusterize

I'm sorry but I really can't help you with this. It works fine with pure js version

**Comment by aeolusheath** [comment]
@NeXTs  thanks

**Comment by Ladvace** [comment]
I have the same problem but in javascript vanilla
