### ISSUE TITLE
Chrome max element height

### ISSUE THREAD

**Issue by stofte** [NeXTs/Clusterize.js#86]
I'm already hitting this limit at 16777200 pixels, a bit from the 134 million for "Blink" (I'm on Chrome v54.0.2840.99 m (64-bit)). The frontpage demo caps out at about 565000 rows, and you cannot scroll to see the last rows any longer.

I was surprised to find the limit so low though. Maybe canvas is the way to go for big data (but what a pain).

**Comment by NeXTs** [comment]
`¯\_(ツ)_/¯`

sad to hear that
