### ISSUE TITLE
insert() or splice() method

### ISSUE THREAD

**Issue by mudcube** [NeXTs/Clusterize.js#88]
One thing that seems to be missing is an `insert()` or `splice()` method. Is this something that would make sense to add to Clusterize, or is there some optimizations that prevent inserting at a specific row index? Also, what's the significance between camelCase and under_score notation in the API?

Btws, I would like to highlight Clusterize is fantastic. I've been rewriting my apps to use for grid-views, lists, and excited to plugin to Infinite Tree soon too. It's perfect in its simplicity and usefulness.

**Comment by NeXTs** [comment]
Hi.

Well, at the moment insert and splice may be emulated by:

```
// pseudocode

var rows = ['<td/>', '<td/>', '<td/>']
var clusterize = new Clusterize({
  rows: rows,
  ...
})

rows.splice(some, magic, here)

clusterize.update(rows)
```


> significance between camelCase and under_score notation in the API

my bad. totally missed that part during development, and then later after publishing I didn't want to break version releasing api changes :\

> It's perfect in its simplicity and usefulness.

Thank you :)

**Comment by mudcube** [comment]
Thank you for your thoughtful response. The solution you provide works well for me. I took a look through the code, and see this is basically the same as it would be implemented internally. I don't believe it's a necessary addition to the API, so am closing this issue.
