### ISSUE TITLE
Too few examples and documentations, scrolling doesn't work

### ISSUE THREAD

**Issue by Edward-Yung** [NeXTs/Clusterize.js#89]
Used a hour to figure out how it works without examples. Btw, scrolling doesn't work on firefox 50.1.0 TT. I think https://github.com/fulmicoton/fattable is much better

**Comment by NeXTs** [comment]
Doesn't work in FF? let me check it

**Comment by NeXTs** [comment]
works for me at ff 50.1.0
what means TT?

**Comment by Edward-Yung** [comment]
It just dun scroll down (the appending data is not showing up). TT = crying

**Comment by Edward-Yung** [comment]
Sorry, accidentally clicked the "closed issue button"

**Comment by NeXTs** [comment]
![fcac91978f30383b104f6cb716036d68](https://cloud.githubusercontent.com/assets/1753208/21286445/88ea49b2-c45c-11e6-909b-bb8211c75559.gif)

**Comment by Edward-Yung** [comment]
I figured out the problem, when I add  
"
        table, th, td {
            border: 0.01px solid dimgray;
            border-collapse: collapse;
        }
"
it just doesn't work.

**Comment by NeXTs** [comment]
works for me
http://codepen.io/NeXTs/pen/dOwqyV

**Comment by Edward-Yung** [comment]
http://codepen.io/Edward-Yung/pen/pNqOyo

**Comment by NeXTs** [comment]
http://codepen.io/NeXTs/pen/jVXvVN?editors=1010

**Comment by Edward-Yung** [comment]
Oh Thanks! I figured it out.
