### ISSUE TITLE
Duplicate rows inserted during 'window resize'

### ISSUE THREAD

**Issue by yarf** [NeXTs/Clusterize.js#98]
Bumped into the following scenario:

I have several "tab" divs in a webpage, where each tab is hidden/shown using "display: block" and "display: none". One of these tabs contains a pair of Clusterize'd tables.

When showing the tab with the table, everything operates as expected. There is one row in each. When switching to another tab (so that now Clusterize is in a 'display:none' div") and then resizing the window, a couple *duplicate* rows are inserted into the Clusterize'd content area. This happens to just one of the tables rather than both, yet both are identical in terms of CSS and styling ('table-layout:fixed').

Inspecting the relevant content-area/rows (in the Browser) shows this happening as soon a resize happens on the "hidden" Clusterize'd table. There are no explicit calls to update() or similar when this occurs, so I'm assuming it's related to the onresize() handler in the plugin? 

Interestingly, a subsequent update() with the original single-row does not clear those additional rows either. It's like they're stuck there once created.

It does appear to be related to Clusterize being rendered inside a hidden div ...

Cheers!

**Comment by NeXTs** [comment]
Codepen example would help a lot

**Comment by yarf** [comment]
http://codepen.io/anon/pen/vgoBQw

Click button at top to switch tabs; then resize window; click again to switch back and see duplicates.

Noticed this does not occur with v0.16.0, FWIW

**Comment by yarf** [comment]
Thanks, though I'm afraid the commit doesn't quite address the issue effectively -- the very next call to update(), either before or after switching back from another tab, causes the same issue to occur.
