### ISSUE TITLE
Looks like the website is broken

### ISSUE THREAD

**Issue by LeCoupa** [NeXTs/Clusterize.js#99]
When I click on process step 3

<img width="516" alt="screen shot 2017-02-21 at 9 46 12 pm" src="https://cloud.githubusercontent.com/assets/1658644/23186472/31f40588-f87f-11e6-8e83-fd419ca5f394.png">

I get this error:

<img width="1223" alt="screen shot 2017-02-21 at 9 46 42 pm" src="https://cloud.githubusercontent.com/assets/1658644/23186487/40ab1eb8-f87f-11e6-9eaa-dc81d37ea263.png">

**Comment by NeXTs** [comment]
Thank you
Have no idea how that happened :\
